# Generated by Django 4.2.18 on 2025-02-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('breed', models.TextField()),
                ('image', models.ImageField(upload_to='cat_images/')),
                ('description', models.TextField()),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
