# Generated by Django 4.2.18 on 2025-02-03 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='image',
        ),
    ]
