# Generated by Django 4.2.18 on 2025-02-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0002_remove_cat_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cat_images/'),
        ),
        migrations.AlterField(
            model_name='cat',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cat',
            name='breed',
            field=models.CharField(max_length=100),
        ),
    ]
