# Generated by Django 4.2.18 on 2025-02-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
