# Generated by Django 4.2.18 on 2025-02-10 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0002_adoptionrequest_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adoptionrequest',
            name='message',
        ),
        migrations.AddField(
            model_name='adoptionrequest',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adoptionrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
