# Generated by Django 4.2.18 on 2025-02-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adoption', '0003_remove_adoptionrequest_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adoptionrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
